config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'portfolio', to: 'pages#portfolio'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        
    end
    
    def portfolio
    
    end

    def about
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EXCELLDEV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="sticky-top border-bottom border-white">
      <nav class="navbar-content d-flex justify-content-between container-fluid">
          <div class="">
            <a class="navbar-brand d-flex navbar-title" href="#"><div>EXCELL</div><div class="color-title">DEV</div></a>
          </div>
          <div>
            <div class="d-flex">
              <div class="nav-item">
                <%= link_to "Home", root_path, class:"nav-link" %>
              </div>
              <div class="nav-item">
                <a class="nav-link" href="#">About</a>
              </div>
              <div class="nav-item">
                <a class="nav-link" href="#">Service</a>
              </div>
              <div class="nav-item">
                <%= link_to "Portfolio", portfolio_path, class:"nav-link" %>
              </div>
              <div class="nav-item">
                  <%= link_to "About", about_path, class:"nav-link" %>
              </div>
            </div>
          </div>
      </nav>
    </header>
    
    <main>
      <div class="my-container">
          <%= yield %>
      </div>
    </main>
    <footer>
      TESTTTT
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
INI ABOUT

app/views/pages/home.html.erb
<div class="height text-center">
    <div class="d-flex justify-content-center semi-bold font-size42"><div> Hi, I'm</div><div class="color-title"> &nbsp;Excell</div></div>
    <div class="font-size20">I'm Web Developer and UI/UX Designer</div>
    <br>
    <%= button_to "About Me", about_path, class: "btn-about semi-bold", method: :get  %>
</div>

app/views/pages/portfolio.html.erb
INI PORTFOLIO